1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
array = np.empty((2,2))
print(array)

[[6.92458792e-310 0.00000000e+000]
 [5.02557535e-091 5.10872151e-066]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
ones_array = np.empty((4,2))
print(ones_array)

[[4.80182333e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


3Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
fill_value = 7
array = np.full((3,3), fill_value)
print(array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
given_array = np.array([[4, 6], [2, 3]], dtype=np.int32)
zeros_array = np.zeros_like(given_array)
print("Given array:")
print(given_array)
print("\nNew array of zeros:")
print(zeros_array)


Given array:
[[4 6]
 [2 3]]

New array of zeros:
[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
given_array = np.array([[4, 9], [5, 10]], dtype=np.float64)
ones_array = np.ones_like(given_array)
print("Given array:")
print(given_array)
print("\nNew array of ones:")
print(ones_array)




Given array:
[[ 4.  9.]
 [ 5. 10.]]

New array of ones:
[[1. 1.]
 [1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)


[1 2 3 4]


4.1.1 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [1]:
import numpy as np
array1 = np.arange(10,50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4.1.2 Create a 3X3 matrix with values ranging from 0 to 8.

In [2]:
import numpy as np
array = np.arange(9) .reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [3]:
import numpy as np
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

In [4]:
import numpy as np
array = np.random.random(50)
mean = array.mean()
print(mean)

0.48181120920174325


# 5. Create a 10X10 array with random values and find the minimum and maximum values.

In [5]:
import numpy as np
array = np.random.random((10,10))
min_value = array.min()
max_value = array.max()
print(min_value)
print(max_value)

0.009475196574187827
0.9980549626000735


# 6. Create a zero array of size 10 and replace 5th element with 1.

In [8]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7. Reverse an array arr = [1,2,0,0,4,0]

In [9]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


# 8.Create a 2d array with 1 on border and 0 inside.

In [10]:
import numpy as np
array = np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 9.Create a 8X8 matrix and fill it with a checkerboard pattern

In [11]:
import numpy as np
array = np.zeros((8,8))
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#1.Add the two array.

In [12]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
sum = array1 + array2
print(sum)

[[ 8 10 12]
 [14 16 18]]


#2.Subtract the two array.

In [13]:
import numpy as np
array1 = np.array([[4,5,6],[7,8,9]])
array2 = np.array([[10,11,12],[13,14,15]])
difference = array1 - array2
print(difference)

[[-6 -6 -6]
 [-6 -6 -6]]


#3. Multiply the array with any integers of your choice.

In [14]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
product = array * 2
print(product)

[[ 2  4  6]
 [ 8 10 12]]


#4. Find the square of each element of the array.

In [15]:
import numpy as np
array = np.array([[4,5,6],[7,8,9]])
square = array ** 2
print(square)

[[16 25 36]
 [49 64 81]]


# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [16]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9, 10])  # Redefine v
w = np.array([11, 12])  # Redefine w
dot_v_w = np.dot(v, w)
print("Dot product of v and w:\n", dot_v_w)
dot_x_v = np.dot(x, v)
print("Dot product of x and v:\n", dot_x_v)

Dot product of v and w:
 219
Dot product of x and v:
 [29 77]


# 6 .Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.

In [17]:
import numpy as np
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_xy_row)
concat_xy_col = np.concatenate((x, y), axis=1)
print("Concatenate x and y along columns:\n", concat_xy_col)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate x and y along columns:
 [[1 2 5 6]
 [3 5 7 8]]


# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [18]:
import numpy as np
try:
    concat_x_v = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error while concatenating x and v:", e)

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.

In [19]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A_inv =\n", identity_matrix)
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A_inv =\n", identity_matrix)

A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


#2. Prove AB ̸= BA.

In [20]:
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal? False


#3. Prove (AB)T= BTAT

In [21]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = np.transpose(AB)

BT_AT = np.dot(B.T, A.T)
print("(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)
print("Are (AB)^T and B^T * A^T equal?", np.array_equal(AB_T, BT_AT))

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal? True
